runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

env_variables:
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:foobar@/postgres?host=/cloudsql/flaskapp-195513:southamerica-east1:postgres-flaskapp

beta_settings:
  cloud_sql_instances: flaskapp-195513:southamerica-east1:postgres-flaskapp
