runtime: python
env: flex
entrypoint: flask run -h 0.0.0.0 -p $PORT

runtime_config:
  python_version: 3

env_variables:
  FLASK_APP: main.py
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:foobar@/postgres?host=/cloudsql/flaskapp-195513:southamerica-east1:postgres-flaskapp

beta_settings:
  cloud_sql_instances: flaskapp-195513:southamerica-east1:postgres-flaskapp
