runtime: python
env: flex

handlers:
- url: /static
  static_dir: static
- url: /.*
script: main.app

runtime_config:
  python_version: 3

env_variables:
  SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:foobar@35.199.87.205/postgres

beta_settings:
  cloud_sql_instances: flaskapp-195513:southamerica-east1:postgres-flaskapp
