runtime: python
env: flex
entrypoint: flask run -h 0.0.0.0 -p $PORT

runtime_config:
  python_version: 3

env_variables:
  FLASK_APP: main.py
  SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:foobar@/mysql?unix_socket=/cloudsql/flaskapp-195513:southamerica-east1:mysql-flaskapp

beta_settings:
  cloud_sql_instances: flaskapp-195513:southamerica-east1:mysql-flaskapp
